# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI/CDd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test
    - run: npm run build
    - name: Create artifact
    - uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: ./build
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            SOURCE: "."
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_PORT: ${{ secrets.PORT }}
            TARGET: '/home/artur/frontend'
            ARGS: "-rltgoDzvO"
